// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $contactos from "./routes/contactos.tsx";
import * as $index from "./routes/index.tsx";
import * as $Agenda from "./islands/Agenda.tsx";
import * as $AgendaManager from "./islands/AgendaManager.tsx";
import * as $DeleteContact from "./islands/DeleteContact.tsx";
import * as $Introducir from "./islands/Introducir.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/contactos.tsx": $contactos,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Agenda.tsx": $Agenda,
    "./islands/AgendaManager.tsx": $AgendaManager,
    "./islands/DeleteContact.tsx": $DeleteContact,
    "./islands/Introducir.tsx": $Introducir,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
